steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["checkout", "main"] # or your default branch
  - name: "python:3.9-slim"
    script: |
      #!/usr/bin/env bash
      pip install -r requirements.txt
      pytest
